name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install mkdocs-simple-hooks
      - run: pip install mkdocs-video
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-with-pdf
      - run: pip install qrcode
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-embed-external-markdown
      - run: pip install mkdocs-include-markdown-plugin
      - run: pip install mkdocs-ezlinks-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-committers-plugin
      - run: pip install mkdocs-exclude
      - run: pip install pptx2md
      - run: pip install mkdocs-macros-plugin
      - run: mkdocs gh-deploy --force
